### ISSUE TITLE
freqtable crashing on DataFrame with no arguments

### ISSUE THREAD

**Issue by bkamins** [nalimilan/FreqTables.jl#17]
@nalimilan Probably because of `@inbounds` on line
https://github.com/nalimilan/FreqTables.jl/blob/master/src/freqtable.jl#L108
the following code fails badly:
```
julia> x = DataFrame(a=repeat([true,false], inner=6), b=repeat([1,2,3], outer=4), c=rand(["p","q"], 12))
12×3 DataFrames.DataFrame
│ Row │ a     │ b │ c │
├─────┼───────┼───┼───┤
│ 1   │ true  │ 1 │ q │
│ 2   │ true  │ 2 │ q │
│ 3   │ true  │ 3 │ q │
│ 4   │ true  │ 1 │ p │
│ 5   │ true  │ 2 │ p │
│ 6   │ true  │ 3 │ p │
│ 7   │ false │ 1 │ q │
│ 8   │ false │ 2 │ p │
│ 9   │ false │ 3 │ q │
│ 10  │ false │ 1 │ p │
│ 11  │ false │ 2 │ q │
│ 12  │ false │ 3 │ p │

julia> freqtable(x)
```
and Julia crashes 😢 because we index outside of array bounds.

**Comment by nalimilan** [comment]
Funny. I guess we just need to define the method taking no additional arguments, and raise an error? It could also be a shorthand for crossing all variables in the data frame, though I'm not sure how useful it is in practice.

**Comment by bkamins** [comment]
I would rather throw an error on `DataFrame`.
On a single argument of vector-like type it work as it does now.

The same problem you have when you call:
```
> freqtable()
```
So probably internal function should be corrected (but you understand the design of the package better than me 😄).

**Comment by nalimilan** [comment]
I agree. The advantage with errors is that you're free to change the behavior later. OTC once you support a method it's hard to get rid of it.

**Comment by bkamins** [comment]
I have pushed PR fixing it.

**Comment by bkamins** [comment]
fixed. closing
