### ISSUE TITLE
`prop` not working with categorical arrays?

### ISSUE THREAD

**Issue by nickeubank** [nalimilan/FreqTables.jl#37]
```
z = CategoricalArray(["a", "a", "b"])

3-element CategoricalArray{String,1,UInt32}:
 "a"
 "a"
 "b"

prop(z)

MethodError: no method matching prop(::CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}})
Closest candidates are:
  prop(!Matched::NamedArrays.NamedArray{#s27,N,AT,DT} where DT where AT where N where #s27<:Number, !Matched::Integer...) at /Users/Nick/.julia/packages/FreqTables/NHPMj/src/freqtable.jl:228
  prop(!Matched::AbstractArray{#s27,N} where N where #s27<:Number) at /Users/Nick/.julia/packages/FreqTables/NHPMj/src/freqtable.jl:220
  prop(!Matched::AbstractArray{#s27,N} where #s27<:Number, !Matched::Integer...) where N at /Users/Nick/.julia/packages/FreqTables/NHPMj/src/freqtable.jl:223

Stacktrace:
 [1] top-level scope at In[63]:1
```

No problems with `freqtable`:

```
freqtable(z)

2-element Named Array{Int64,1}
Dim1  │ 
──────┼──
a     │ 2
b     │ 1
```

**Comment by nalimilan** [comment]
`prop` computes proportions, so it needs `Number` entries (as documented).

**Comment by nickeubank** [comment]
OH! I see -- prop doesn't calculate proportions directly, it takes a frequency table as an input. 

Out of curiosity, why the second step? why is it `prop(freqtable(df, :some_var))` instead of just having `prop` work like `freqtable`, just with proportions rather than counts?

**Comment by nalimilan** [comment]
See https://github.com/nalimilan/FreqTables.jl/pull/19 and https://github.com/nalimilan/FreqTables.jl/issues/8. We can add `proptable` as a shorthand, but `prop` is useful in its own right so it was a good first step anyway.

**Comment by nickeubank** [comment]
Ah, ok. Yes, I think `proptable` would be a really nice function!

**Comment by nalimilan** [comment]
Feel free to make a PR if you want.

**Comment by nickeubank** [comment]
#38
