### ISSUE TITLE
Feature Request: Export

### ISSUE THREAD

**Issue by ClimateNexus** [nalimilan/FreqTables.jl#41]
Hey guys.  Nice work on this.  Really helps to quickly run tables of weighted survey data instead of using a tapply approach.  I'm a little new to Julia, as we're looking to transition away from R.  Would it be possible to include an export function either to HTML/LATEX or be able to convert the table dataframe? (in R it would be something like as.data.frame.matrix().) Thanks.

**Comment by nalimilan** [comment]
That's something to ask in NamedArrays. This package's goal is only to create the table from raw data.
