### ISSUE TITLE
Frequency tables for non-ordered types

### ISSUE THREAD

**Issue by bjncn** [nalimilan/FreqTables.jl#5]
`dimnames = sort!(unique(s))` on line 195 of freqtable.jl implies that an error will be triggered when computing frequency tables of non-ordered objects (example: my use case was for an array of sets).

**Comment by nalimilan** [comment]
Indeed. We may as well keep the values in their original order.

**Comment by nalimilan** [comment]
Actually, I found a better fix: we can simply check whether `isless` can be applied or not. Please report if this works for you.

**Comment by bjncn** [comment]
It does:

~~~
> FreqTables.freqtable([1,"yes"])
2-element NamedArrays.NamedArray{Int64,1,Array{Int64,1},Tuple{Dict{Any,Int64}}}
yes 1
1   0
~~~

Thanks a lot!

**Comment by bjncn** [comment]
Adding a random thought: sorting on the count is always possible and might be a goof fall-back option or even a good keyword option to have.

**Comment by nalimilan** [comment]
Cool. I think sorting on counts should be done manually when applicable.
