### ISSUE TITLE
Allow strings for column names

### ISSUE THREAD

**Issue by pdeffebach** [nalimilan/FreqTables.jl#51]
`freqtable(df, "var")` gives a method errod. 

Now that DataFrames allows for `String` indexing it would be nice if this did as well.

**Comment by nalimilan** [comment]
Right. That shouldn't be too hard. Would you make a PR?

**Comment by bkamins** [comment]
bump - just hit this when doing PyData Global tutorial

**Comment by nalimilan** [comment]
See https://github.com/nalimilan/FreqTables.jl/pull/53.
