### ISSUE TITLE
NamedArrays.jl compat

### ISSUE THREAD

**Issue by bkamins** [nalimilan/FreqTables.jl#69]
@nalimilan - can we allow NamedArrays.jl 0.10.0? I think it should be OK

**Comment by nalimilan** [comment]
Good point. CompatHelper got disabled due to inactivity. See https://github.com/nalimilan/FreqTables.jl/pull/70.

**Comment by nalimilan** [comment]
https://github.com/JuliaRegistries/General/pull/91551
