### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by diegozea** [nalimilan/FreqTables.jl#9]
This error depends on the order of the columns:

```julia
using RDatasets
titanic = dataset("COUNT","titanic")
using FreqTables
freqtable(titanic, :Sex, :Class, :Survived)
```
Error with this order (works fine with other order):
```
KeyError: 2 not found

 in indices at /home/diego/.julia/v0.4/NamedArrays/src/index.jl:33
 in getindex at /home/diego/.julia/v0.4/NamedArrays/src/index.jl:20
 in show at /home/diego/.julia/v0.4/NamedArrays/src/show.jl:40
 in writemime at /home/diego/.julia/v0.4/NamedArrays/src/show.jl:18
 in writemime at multimedia.jl:43
 in sprint at iostream.jl:206
 in display_dict at /home/diego/.julia/v0.4/IJulia/src/execute_request.jl:26
```

**Comment by nalimilan** [comment]
Thanks for the catching this. This is again a bug in NamedArrays.jl, where the display of 3-way tables has been improved recently. So please report it there, linking back to this issue.

**Comment by diegozea** [comment]
I won't be at home until Monday. Could you open that issue there? Thanks!

**Comment by nalimilan** [comment]
There's no hurry, it can wait until Monday.

**Comment by nalimilan** [comment]
@davidavdav Could you have a look at this? Thanks!

**Comment by davidavdav** [comment]
ok, I will.

**Comment by davidavdav** [comment]
Thanks for revealing the bug.  I used CartesianIndex the wrong way.
